var PDF_URL="assets/Krupali_Dhangar_Resume.pdf";

var E=function(i){return document.getElementById(i)};
var chips=function(a){return '<div class="chips">'+a.map(function(s){return '<span class="chip">'+s+'</span>'}).join('')+'</div>'};
E('pillars').innerHTML=[["01","Full-stack development","Responsive React front-ends backed by Node, Express, REST APIs and MongoDB / PostgreSQL.","b3"],["02","Data analytics & BI","KPI design, DAX modelling and dashboards that turn raw data into decisions.","b2"],["03","ML & AI engineering","End-to-end NLP and regression pipelines from preprocessing to evaluation.","b4"]].map(function(p){return '<div class="card '+p[3]+'"><div class="m" style="color:var(--mu);font-size:13px">'+p[0]+'</div><h3 style="font-size:26px">'+p[1]+'</h3><p>'+p[2]+'</p></div>'}).join('');
E('edu').innerHTML=[["2023 – 2027","MPSTME, NMIMS University",["B.Tech in Information Technology","CGPA 3.03/4 (7.58/10)"],"b1"],["2021 – 2023","Dr. C.G. Tele Junior College, Thalner",["HSC","80.5%"],"b2"],["2020 – 2021","H. R. Patel Higher Secondary School, Shirpur",["SSC","89.6%"],"b4"]].map(function(e){return '<div class="card '+e[3]+'"><div class="lab">'+e[0]+'</div><h3>'+e[1]+'</h3>'+chips(e[2])+'</div>'}).join('');
E('skills').innerHTML=[["Languages",["Java","Python","SQL"],"b3"],["Data & BI",["Power BI","Excel","Tableau","Google Analytics","Data Visualization","EDA"],"b2"],["Databases",["MySQL","MS SQL Server","PostgreSQL"],"b4"],["Web",["HTML","CSS","JavaScript","Material UI","UI/UX"],"b1"],["Core CS",["DSA","OOP","CN","OS","DBMS"],"b1"],["Tools",["GitHub","VS Code","Google Colab","Jupyter","Figma","PowerPoint"],"b3"],["Enterprise",["SAP Analytics Cloud","SAP Business Data Cloud","Google Workspace"],"b4"],["AI Tools",["ChatGPT","Claude","Gemini","Cursor AI","Copilot","Perplexity AI"],"b2"]].map(function(s){return '<div class="card '+s[2]+'" style="padding:24px"><div class="lab" style="margin-bottom:16px">'+s[0]+'</div>'+chips(s[1])+'</div>'}).join('');
E('soft').innerHTML=["Data analysis","Troubleshooting","Cross-team coordination","Written & verbal communication","User training & support","Root cause analysis","Scheduling & prioritization","Workflow adaptation","Project coordination","Logical reasoning","Client support","Technical writing","Stakeholder collaboration"].map(function(s){return '<span class="chip" style="font-size:12px;padding:8px 16px">'+s+'</span>'}).join('');
E('certs').innerHTML=[["Managing Projects with AI","AI CERTs — Coursera","Aug 2026"],["AWS Certified Training – Fundamentals of ML & AI","AWS","Jul 2026"],["AWS Educate: Introduction to Cloud 101","AWS Training and Certification","Jul 2026"],["Delta – Full Stack Web Development","Apna College","Jul 2026"],["SAP Analytics Cloud – Security & Administration","SAP","Jun 2026"],["SAP Business Data Cloud – Advanced Data Architecture","SAP","Jun 2026"],["Siemens Project Manager Job Simulation","Forage","May 2026"],["Career Essentials in Business Analysis","Microsoft & LinkedIn","Jul 2025"],["Deloitte Australia – Data Analyst Job Simulation","Forage","Jun 2025"],["Google Analytics Certification","Google","May 2025"]].map(function(c,i){return '<div class="rowc"><span class="m n">'+String(i+1).padStart(2,"0")+'</span><b>'+c[0]+'</b><small>'+c[1]+'</small><span class="m" style="font-size:12px;color:var(--mu)">'+c[2]+'</span></div>'}).join('');
E('wins').innerHTML=[["MAR 2025","2nd runner-up · 24-hour Hackathon","NMIMS MPSTME — troubleshooting, team collaboration and technical skill under pressure.","b4"],["DEC 2025","College Ambassador · Techfest IIT Bombay","Represented the institution at Asia's largest science & technology festival; global rank under 12,000.","b3"],["MAR 2026","SAS Curiosity Cup 2026 Participant","Strengthened data analysis and problem-solving through real-world business data challenges.","b2"],["MAY 2026","Siemens Project Manager Simulation","KPI development and project-dashboard management tasks simulating real project workflows.","b1"],["JUN 2025","TCS iQN Career Edge · Young Professional","Certified in soft skills, AI fundamentals, business etiquette and IT foundational skills.","b2"],["ONGOING","National-level hackathons","Shortlisted for developing software solutions to real-world challenges.","b3"]].map(function(w){return '<div class="card '+w[3]+'"><div class="lab" style="color:var(--mu)">'+w[0]+'</div><h3 style="font-size:19px">'+w[1]+'</h3><p style="margin:0">'+w[2]+'</p></div>'}).join('');
E('projs').innerHTML=[["ML · NLP","Air & Noise Pollution Complaint Analysis System","Classifies citizen complaints, identifies priority patterns and generates actionable insights for faster environmental decision-making.",["Python","NLTK","TF-IDF","Linear SVM","BiLSTM","BERT","FastAPI","PostgreSQL","React.js"],"b1"],["Full-stack","Real-Time Video Conferencing App","Authentication, meeting rooms, audio/video calling, screen sharing, chat and meeting history via REST APIs, WebRTC and Socket.IO.",["React.js","Node.js","Express.js","MongoDB","Material UI"],"b3"],["Data & BI","Procurement KPI Analysis","777+ purchase orders across 50+ suppliers → $750K+ savings found. 15+ KPIs, 4-page dashboard, 25+ DAX measures; manual reporting cut by 80%.",["Python","Pandas","Power BI","DAX","Google Colab"],"b2"],["Data & BI","Global CO₂ Emissions Dashboard","5-page interactive dashboard with drill-through and a 5-table Galaxy Schema across 50+ countries, 7 regions and 1950–2023 data.",["Power BI","DAX","Power Query","Data Modeling"],"b2"],["AI · MERN","SigmaGPT","ChatGPT-inspired full-stack app with AI conversations, OpenAI API integration, RESTful APIs and a responsive React interface.",["MongoDB","Express.js","React.js","Node.js","OpenAI API"],"b4"],["ML & AI","Amazon E-Commerce Profitability Prediction","Supervised regression pipeline on 128K+ records; Lasso, Decision Tree, Random Forest and XGBoost compared with RMSE, R² and 5-fold CV.",["Python","EDA","XGBoost","Random Forest"],"b1"],["Full-stack","Automated Timetable Management System","Conflict-free allocation of subjects, faculty, classrooms and time slots — cutting manual scheduling effort.",["PHP","MySQL","JavaScript","HTML5","CSS3"],"b3"],["Databases","Bank Loan Approval & Performance Tracking","600+ loan records analysed in PostgreSQL with a normalized schema, ETL pipeline, ACID transactions and 10+ credit-risk insights.",["PostgreSQL","SQL","ETL","Joins"],"b4"],["Data & BI","EV Population Analytics Dashboard","Interactive Tableau dashboard on U.S. electric-vehicle adoption trends, geography and manufacturer performance.",["Tableau","Excel","KPIs"],"b2"],["Core CS","Personal Finance Manager","Menu-driven Java console app for income/expense tracking, balances and categorized transactions with CRUD on ArrayList.",["Java","OOP","Collections"],"b3"],["Frontend","Chess Game","Interactive chess with move validation, captures, castling, move highlighting, theme switching and animations.",["HTML","CSS","JavaScript","jQuery"],"b1"]].map(function(p,i){return '<article class="card '+p[4]+'"><div class="top"><span class="chip">'+p[0].toUpperCase()+'</span><span class="m">'+String(i+1).padStart(2,"0")+'</span></div><h3>'+p[1]+'</h3><p>'+p[2]+'</p>'+chips(p[3])+'</article>'}).join('');
/* navigation: click a header button -> smooth-scroll to that section */
function go(id){var el=E(id);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('#nav a').forEach(function(a){a.addEventListener('click',function(){go(a.dataset.s);});});
document.querySelectorAll('[data-go]').forEach(function(a){a.addEventListener('click',function(){go(a.dataset.go);});});
var ids=['home','about','projects','resume','contact'];
function setOn(id){document.querySelectorAll('#nav a').forEach(function(a){a.classList.toggle('on',a.dataset.s===id);});}
function spy(){var y=window.scrollY+140,cur='home';ids.forEach(function(i){var el=E(i);if(el&&el.offsetTop<=y)cur=i;});
 if(window.innerHeight+window.scrollY>=document.body.scrollHeight-4)cur='contact';setOn(cur);}
window.addEventListener('scroll',spy,{passive:true});spy();
/* resume download / open */
function dl(){var m=E('rmsg');try{var a=document.createElement('a');a.href=PDF_URL;a.download='Krupali_Dhangar_Resume.pdf';document.body.appendChild(a);a.click();a.remove();m.textContent='Thanks for downloading!';}catch(e){m.textContent='Could not start the download. Please try again.';}}
E('hdl').addEventListener('click',function(){go('resume');dl();});
E('dl2').addEventListener('click',dl);
E('open').addEventListener('click',function(){var w=null;try{w=window.open(PDF_URL,'_blank');}catch(e){}
 if(!w){E('rmsg').textContent='Your browser blocked the new tab. Use Download PDF instead.';}});
E('send').addEventListener('click',function(){var n=E('fn').value,e=E('fe').value,m=E('fm').value;
 var a=document.createElement('a');a.href='mailto:krupalidhangar@gmail.com?subject='+encodeURIComponent('Portfolio message from '+(n||'a visitor'))+'&body='+encodeURIComponent(m+'\n\n'+n+(e?' ('+e+')':''));a.target='_blank';a.click();});
